dist: trusty
sudo: required
language: node_js
node_js:
  - "6.9.1"
addons:
  sonarcloud:
    organization: "arpitajava-github"
    token:
      secure: "e23c3d96b07f1695817c36dc3a34962582a926bd"
script:
  - sonar-scanner
  - npm test
  - npm run gbuild
  - npm install -g istanbul
  - istanbul cover node_modules/mocha/bin/_mocha test/*.js
  - test -d coverage
  - istanbul report --dir coverage --include **/*coverage.json lcov

cache:
  directories:
    - '$HOME/.sonar/cache'