dist: trusty
sudo: false
language: node_js
node_js:
  - "6.9.1"
addons:
  sonarcloud:
    organization: "arpitajava-github"
    token:
      secure: "e23c3d96b07f1695817c36dc3a34962582a926bd"
script:
  - sonar-scanner
  - npm test
  - npm run gbuild
  - echo "Travis branch is $TRAVIS_BRANCH"
after_script:
  - npm run-script coveralls
after_success:
  - push.sh
  - ./bin/codecov -e v6.9.1 -f coverage/coverage.json

cache:
  directories:
    - '$HOME/.sonar/cache'
