dist: trusty
sudo: false

script:
  - travis-encrypt -r -a arpitajava/ZynlaNew ENV1=15a0714b8af5a5ed18979434719c2d6ea35a4b52 
  - echo ENV1=15a0714b8af5a5ed18979434719c2d6ea35a4b52 | ./coverage/arpita.json -r arpitajava/ZynlaNew