dist: trusty
sudo: false
language: node_js
node_js:
  - "6.9.1"

before_install:
  - chmod +x ./coverage/arpita.json

script:
  - npm install travis-encrypt -g GH_TOKEN=15a0714b8af5a5ed18979434719c2d6ea35a4b52
  - echo GH_TOKEN=15a0714b8af5a5ed18979434719c2d6ea35a4b52 | ./coverage/arpita.json -r arpitajava/ZynlaNew