dist: trusty
sudo: false
language: node_js
node_js:
  - "6.9.1"
addons:
  sonarcloud:
    organization: "arpitajava-github"
    token:
      secure: "e23c3d96b07f1695817c36dc3a34962582a926bd"
script:
  - sonar-scanner
  - npm test
  - npm run gbuild
  - npm install -g istanbul
  - istanbul cover node_modules/mocha/bin/_mocha test/*.js
  - npm install coveralls --save-dev
  - istanbul report --dir coverage --include **/*coverage.json lcov
  - echo "Travis branch is $TRAVIS_BRANCH"
env:
  global:
  - secure: d8d1021e68506dd9d2a0595f4572115fdd6b362e
after_script:
    - npm run-script coveralls
after_success:
  -  git config --global user.email "alivewithme@gmail.com"
  -  git config --global user.name "arpitajava"
  -  git config --global user.pass "Arpitadas1234"
  -  git config --global -l
  -  git status
  -  git add .
  -  git commit -m "Travis build"
  -  git push origin master
