dist: trusty
sudo: false
language: node_js
node_js:
  - "6.9.1"
addons:
  sonarcloud:
    organization: "arpitajava-github"
    token:
      secure: "e23c3d96b07f1695817c36dc3a34962582a926bd"
script:
  - sonar-scanner
  - npm test
  - npm run gbuild
  - npm install -g istanbul
  - istanbul cover node_modules/mocha/bin/_mocha test/*.js
  - npm install coveralls --save-dev
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - echo "Travis branch is $TRAVIS_BRANCH"
after_script:
  - npm run-script coveralls
before_install:
  - chmod +x push.sh
  - cd ZynlaNew
after_success:
  - ./push.sh

cache:
  directories:
    - '$HOME/.sonar/cache'
