dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "arpitajava-github"
    token:
      secure: "e23c3d96b07f1695817c36dc3a34962582a926bd"

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'