dist: trusty
sudo: false
language: node_js
node_js:
  - "6.9.1"
addons:
  sonarcloud:
    organization: "arpitajava-github"
    token:
      secure: "e23c3d96b07f1695817c36dc3a34962582a926bd"
script:
  - travis-encrypt -r -a arpitajava/ZynlaNew ENV1=15a0714b8af5a5ed18979434719c2d6ea35a4b52 
  - echo ENV1=15a0714b8af5a5ed18979434719c2d6ea35a4b52 | ./coverage/arpita.json -r arpitajava/ZynlaNew